version: "1.0"
lastModified: 2025-08-06T15:30:49.378Z
cost:
  profiles:
    - mks-master
  services: []
  start_date: 2025-01-01
  end_date: 2025-07-24
  period: monthly
  exclude_taxes: true
  exclude_support: true
security:
  profiles:
    - mks-vizcon
  home_region: eu-west-1
multiProviderSSO:
  version: "1.0"
  lastModified: 2025-08-06T15:30:49.376Z
  providers:
    - id: sso-mksolutions
      type: AWS_SSO
      name: AWS SSO - mksolutions
      settings:
        startUrl: https://mksolutions.awsapps.com/start/
        region: eu-west-1
        organizationName: mksolutions
        profiles:
          - profileName: mks-master
            accountId: "197649153002"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-operations
            accountId: "975050133730"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-dev
            accountId: "144772444743"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-prod
            accountId: "118075612719"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-prod-legacy
            accountId: "533235459606"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-demo
            accountId: "600668649017"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-demo-network
            accountId: "797160173484"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-vizcon
            accountId: "816069133418"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-vizcon-customer
            accountId: "451947743928"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-vizcon-dev
            accountId: "893256823264"
            roleName: Admin
            region: eu-west-1
          - profileName: mks-hicham
            accountId: "888744242498"
            roleName: Admin
            region: eu-west-1
          - profileName: VizCon-DNSAdministrator
            accountId: "816069133418"
            roleName: DNSAdministrator
            region: eu-west-1
      security:
        sslVerification: true
        tokenEncryption: true
        sessionBinding: true
        auditLogging: true
      proxy:
        enabled: false
    - id: sso-arktos
      type: AWS_SSO
      name: AWS SSO - arktos
      settings:
        startUrl: https://arktos.awsapps.com/start/
        region: eu-west-1
        organizationName: arktos
        profiles:
          - profileName: arktos-master
            accountId: "555619946347"
            roleName: Administrator
            region: eu-west-1
          - profileName: arktos-prod
            accountId: "753892334693"
            roleName: Administrator
            region: eu-west-1
      security:
        sslVerification: true
        tokenEncryption: true
        sessionBinding: true
        auditLogging: true
      proxy:
        enabled: false
  globalSettings:
    security:
      sslVerification: true
      tokenEncryption: true
      sessionBinding: true
      auditLogging: true
