// AWS Service options for cost reporting
// These are the most common AWS services that appear in cost reports

export const AWS_SERVICES = [
  'Amazon API Gateway',
  'Amazon Athena',
  'Amazon Certificate Manager',
  'Amazon CloudFront',
  'Amazon CloudWatch',
  'Amazon CloudWatch Logs',
  'Amazon Cognito',
  'Amazon DynamoDB',
  'Amazon ElastiCache',
  'Amazon Elastic Compute Cloud - Compute',
  'Amazon Elastic Container Service',
  'Amazon Elastic File System',
  'Amazon Elastic Kubernetes Service',
  'Amazon Elastic Load Balancing',
  'Amazon GuardDuty',
  'Amazon Inspector',
  'Amazon Kinesis',
  'Amazon Macie',
  'Amazon OpenSearch Service',
  'Amazon Redshift',
  'Amazon Relational Database Service',
  'Amazon Route 53',
  'Amazon Simple Email Service',
  'Amazon Simple Notification Service',
  'Amazon Simple Queue Service',
  'Amazon Simple Storage Service',
  'Amazon Virtual Private Cloud',
  'AmazonCloudWatch',
  'AWS Backup',
  'AWS Certificate Manager',
  'AWS CloudFormation',
  'AWS CloudTrail',
  'AWS CodeBuild',
  'AWS CodeCommit',
  'AWS CodeDeploy',
  'AWS CodePipeline',
  'AWS Config',
  'AWS Cost Explorer',
  'AWS Fargate',
  'AWS Glue',
  'AWS Identity and Access Management',
  'AWS Key Management Service',
  'AWS Lambda',
  'AWS Secrets Manager',
  'AWS Security Hub',
  'AWS Step Functions',
  'AWS Support (Basic)',
  'AWS Support (Business)',
  'AWS Support (Developer)',
  'AWS Support (Enterprise)',
  'AWS Systems Manager',
  'AWS Transfer Family',
  'AWS WAF',
  'CloudWatch Events',
  'EC2 - Other',
  'Elastic Load Balancing',
  'Tax'
].sort(); // Sort alphabetically

// Convert to options format for Ant Design Select component
export const AWS_SERVICE_OPTIONS = AWS_SERVICES.map(service => ({
  label: service,
  value: service,
}));